#!/usr/bin/env python3
"""
nyx-p1-001: Generate the Glitch Echo (GLCH) commodity sprite.

Outputs:
  assets/commodities/glitch_echo.png            1024x1024  HD source
  assets/optimized/commodities/glitch_echo.png   256x256   In-app optimized

Lore: Glitch Echoes are crystallised AI-fragment shockwaves harvested from
S1LKROAD 4.0 archive collisions — Eidolon afterimages frozen at the moment
two shards desync. Mid-volatility, mid-heat-risk; ai_fragment + drift tags.

Provenance: internally generated by Nyx/Palette via Python Pillow on
2026-04-29. No external assets, stock art, or licensed imagery.
"""

import math
import os
import random
from PIL import Image, ImageDraw, ImageFilter

ROOT = os.path.join(os.path.dirname(__file__), "..")
HD_OUT = os.path.join(ROOT, "assets", "commodities", "glitch_echo.png")
OPT_OUT = os.path.join(ROOT, "assets", "optimized", "commodities", "glitch_echo.png")

os.makedirs(os.path.dirname(HD_OUT), exist_ok=True)
os.makedirs(os.path.dirname(OPT_OUT), exist_ok=True)


# Palette — CyberTrader cyan accent, dark void, plus glitch RGB-shift triad
BG_DEEP    = (5, 6, 8)            # #050608 deep-space black
CYAN       = (0, 255, 204)        # #00FFCC primary accent
MAGENTA    = (255, 64, 192)       # #FF40C0 chromatic-aberration shift
AMBER      = (255, 200, 64)       # #FFC840 spectrum drift highlight
RING       = (26, 31, 58)         # #1A1F3A dark navy structural line
DIM        = (0, 153, 122)        # #00997A muted accent


def render(size: int) -> Image.Image:
    """Render the GLCH sprite at the requested square pixel size.

    Composition layers:
      1. Deep-void radial background.
      2. Hex circuit lattice (matches brand mark).
      3. Three RGB-shifted concentric rings (the "echo").
      4. Glitch shard core silhouette in cyan with magenta+amber chromatic aberration.
      5. Scan-line corruption strip across the lower third.
    """
    rng = random.Random(910410)  # deterministic seed; never changes by run.
    img = Image.new("RGBA", (size, size), BG_DEEP + (255,))
    draw = ImageDraw.Draw(img, "RGBA")

    cx = cy = size / 2

    # 1. Radial vignette via concentric darkening rings (cheap, no numpy).
    max_r = int(size * 0.7)
    for r in range(max_r, 0, -2):
        alpha = int(8 * (1 - r / max_r))
        draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=(0, 26, 32, alpha))

    # 2. Hex lattice.
    hex_r = size * 0.06
    hex_w = hex_r * math.sqrt(3)
    rows = int(size / hex_r) + 4
    cols = int(size / hex_w) + 4
    for row in range(-2, rows):
        for col in range(-2, cols):
            x = col * hex_w + (hex_w / 2 if row % 2 else 0)
            y = row * hex_r * 1.5
            points = [
                (x + hex_r * math.cos(math.radians(a)),
                 y + hex_r * math.sin(math.radians(a)))
                for a in range(0, 360, 60)
            ]
            draw.line(points + [points[0]], fill=RING + (90,), width=max(1, size // 256))

    # 3. RGB-shifted concentric "echo" rings.
    for offset, color in ((-size * 0.012, MAGENTA), (0, CYAN), (size * 0.012, AMBER)):
        for k, scale in enumerate((0.40, 0.32, 0.24)):
            r = size * scale
            box = (cx - r + offset, cy - r, cx + r + offset, cy + r)
            draw.ellipse(box, outline=color + (180 - k * 30,), width=max(2, size // 200))

    # 4. Glitch shard core — overlapping triangles.
    core_r = size * 0.18
    triangle_a = [
        (cx, cy - core_r),
        (cx - core_r * 0.85, cy + core_r * 0.7),
        (cx + core_r * 0.85, cy + core_r * 0.7),
    ]
    triangle_b = [
        (cx, cy + core_r),
        (cx - core_r * 0.85, cy - core_r * 0.7),
        (cx + core_r * 0.85, cy - core_r * 0.7),
    ]
    draw.polygon(triangle_a, outline=CYAN, fill=(0, 255, 204, 120),
                 width=max(2, size // 160))
    draw.polygon(triangle_b, outline=MAGENTA, fill=(255, 64, 192, 70),
                 width=max(2, size // 160))

    # 5. Scan-line corruption band (lower third).
    band_top = int(size * 0.62)
    band_bottom = int(size * 0.78)
    for y in range(band_top, band_bottom, max(1, size // 128)):
        if rng.random() < 0.55:
            x0 = rng.randint(0, size // 4)
            x1 = size - rng.randint(0, size // 4)
            color = rng.choice((CYAN, MAGENTA, AMBER))
            draw.line(((x0, y), (x1, y)), fill=color + (150,), width=max(1, size // 256))

    # Subtle bloom.
    glow = img.filter(ImageFilter.GaussianBlur(radius=max(2, size // 96)))
    final = Image.alpha_composite(glow, img)

    # Glyph: GLCH text in lower-center, cyan with magenta chromatic-aberration ghost.
    label_offset = int(size * 0.36)
    try:
        # ImageDraw default font scales poorly; draw simple block letters via lines.
        glyph = "GLCH"
        glyph_size = max(6, size // 14)
        glyph_w = glyph_size * len(glyph) * 0.62
        gx = cx - glyph_w / 2
        gy = cy + label_offset
        ghost_layer = Image.new("RGBA", final.size, (0, 0, 0, 0))
        ghost_draw = ImageDraw.Draw(ghost_layer, "RGBA")
        ghost_draw.text((gx + max(2, size // 256), gy), glyph,
                        fill=MAGENTA + (180,))
        ghost_draw.text((gx - max(2, size // 256), gy), glyph,
                        fill=AMBER + (160,))
        ghost_draw.text((gx, gy), glyph, fill=CYAN + (240,))
        final = Image.alpha_composite(final, ghost_layer)
    except Exception:
        pass

    return final


def main() -> None:
    hd = render(1024)
    hd.save(HD_OUT, "PNG", optimize=True)
    print(f"  wrote {HD_OUT} ({os.path.getsize(HD_OUT)} bytes)")

    opt = render(256)
    opt.save(OPT_OUT, "PNG", optimize=True)
    print(f"  wrote {OPT_OUT} ({os.path.getsize(OPT_OUT)} bytes)")


if __name__ == "__main__":
    main()
