#!/usr/bin/env python3
"""
palette-p1-002: Generate placeholder icon and splash brand assets for CyberTrader.

Outputs (all in assets/brand/):
  icon.png             1024×1024  App Store / Play Store icon source
  adaptive-icon.png    1024×1024  Android adaptive icon foreground (transparent bg)
  splash.png           1284×2778  Splash screen (iPhone 14 Pro portrait baseline)
  favicon.png            64×64   Web favicon

Design language: deep-space dark background (#050608), CyberTrader cyan (#00FFCC),
hexagonal circuit motif, "CT" mark — matches the app's diegetic aesthetic.

Provenance: internally generated by Palette/Zara on 2026-04-26 using Python Pillow.
No external assets, stock art, or licensed imagery. Free to use for all store surfaces.
"""

import math
import os
import sys
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "brand")
os.makedirs(OUT_DIR, exist_ok=True)

# ── Palette ────────────────────────────────────────────────────────────────────
BG      = (5, 6, 8)          # #050608  deepspace black
CYAN    = (0, 255, 204)      # #00FFCC  primary accent
DIM     = (0, 153, 122)      # #00997A  muted accent
RING    = (26, 31, 58)       # #1A1F3A  dark navy ring
WHITE   = (255, 255, 255)
TRANS   = (0, 0, 0, 0)


def hexagon_points(cx, cy, r, flat_top=False):
    """Return 6 (x,y) vertices of a regular hexagon."""
    offset = 0 if flat_top else math.pi / 6
    return [
        (cx + r * math.cos(math.pi / 3 * i + offset),
         cy + r * math.sin(math.pi / 3 * i + offset))
        for i in range(6)
    ]


def draw_circuit_ring(draw, cx, cy, radius, color, width=4, n_nodes=6):
    """Draw a dashed hex ring with small node squares at vertices."""
    pts = hexagon_points(cx, cy, radius)
    for i in range(n_nodes):
        x0, y0 = pts[i]
        x1, y1 = pts[(i + 1) % n_nodes]
        # dashed line: 3 segments per edge
        segs = 6
        for s in range(segs):
            if s % 2 == 0:
                t0 = s / segs
                t1 = (s + 0.7) / segs
                draw.line(
                    (x0 + (x1 - x0) * t0, y0 + (y1 - y0) * t0,
                     x0 + (x1 - x0) * t1, y0 + (y1 - y0) * t1),
                    fill=color, width=width
                )
        # node
        nr = width * 2.5
        draw.ellipse((x1 - nr, y1 - nr, x1 + nr, y1 + nr), fill=color)


def draw_icon_base(draw, size, bg=BG, ring_color=RING, accent=CYAN, dim=DIM):
    """Shared icon design: concentric hex rings + CT mark."""
    cx, cy = size / 2, size / 2
    scale = size / 1024

    # Outer filled hex (nav area)
    outer_r = size * 0.47
    draw.polygon(hexagon_points(cx, cy, outer_r), fill=ring_color)

    # Inner filled hex (core area)
    inner_r = size * 0.33
    draw.polygon(hexagon_points(cx, cy, inner_r), fill=bg)

    # Circuit rings
    draw_circuit_ring(draw, cx, cy, size * 0.44, accent, width=max(2, int(4 * scale)), n_nodes=6)
    draw_circuit_ring(draw, cx, cy, size * 0.31, dim,   width=max(1, int(2 * scale)), n_nodes=6)

    # Centre dot
    dot_r = size * 0.05
    draw.ellipse((cx - dot_r, cy - dot_r, cx + dot_r, cy + dot_r), fill=accent)

    # "CT" text mark — use built-in font sized to ~25% of icon width
    font_size = max(16, int(size * 0.20))
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Courier New Bold.ttf", font_size)
    except Exception:
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Monaco.ttf", font_size)
        except Exception:
            font = ImageFont.load_default()

    label = "CT"
    bbox = draw.textbbox((0, 0), label, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text((cx - tw / 2, cy - th / 2 - int(size * 0.01)), label, fill=CYAN, font=font)

    # Small horizontal accent bar below text
    bar_w, bar_h = size * 0.12, max(2, int(3 * scale))
    draw.rectangle(
        (cx - bar_w, cy + th / 2 + int(size * 0.03),
         cx + bar_w, cy + th / 2 + int(size * 0.03) + bar_h),
        fill=DIM
    )


# ── 1. icon.png (1024×1024, opaque) ───────────────────────────────────────────
SIZE = 1024
img = Image.new("RGB", (SIZE, SIZE), BG)
draw = ImageDraw.Draw(img)
draw_icon_base(draw, SIZE)
out = os.path.join(OUT_DIR, "icon.png")
img.save(out, "PNG", optimize=True)
print(f"wrote {out}  ({os.path.getsize(out):,} bytes)")

# ── 2. adaptive-icon.png (1024×1024, transparent bg) ──────────────────────────
img2 = Image.new("RGBA", (SIZE, SIZE), TRANS)
draw2 = ImageDraw.Draw(img2)
draw_icon_base(draw2, SIZE, bg=(0, 0, 0, 0), ring_color=(*RING, 255), accent=CYAN, dim=DIM)
out2 = os.path.join(OUT_DIR, "adaptive-icon.png")
img2.save(out2, "PNG", optimize=True)
print(f"wrote {out2}  ({os.path.getsize(out2):,} bytes)")

# ── 3. splash.png (1284×2778 portrait, opaque) ────────────────────────────────
SW, SH = 1284, 2778
splash = Image.new("RGB", (SW, SH), BG)
sd = ImageDraw.Draw(splash)

# Subtle horizontal scan-lines (every 8px, very dark)
for y in range(0, SH, 8):
    sd.line([(0, y), (SW, y)], fill=(10, 12, 16), width=1)

# Centre icon badge
badge_size = int(SW * 0.55)  # ~706px
badge = Image.new("RGB", (badge_size, badge_size), BG)
bd = ImageDraw.Draw(badge)
draw_icon_base(bd, badge_size)
bx = (SW - badge_size) // 2
by = (SH - badge_size) // 2 - int(SH * 0.06)
splash.paste(badge, (bx, by))

# App name below badge
try:
    title_font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Courier New Bold.ttf", 72)
    sub_font   = ImageFont.truetype("/System/Library/Fonts/Supplemental/Courier New.ttf", 36)
except Exception:
    title_font = ImageFont.load_default()
    sub_font   = title_font

title = "CYBERTRADER"
tb = sd.textbbox((0, 0), title, font=title_font)
tw = tb[2] - tb[0]
tx = (SW - tw) // 2
ty = by + badge_size + int(SH * 0.025)
sd.text((tx, ty), title, fill=CYAN, font=title_font)

sub = "AGE OF PANTHEON"
sb = sd.textbbox((0, 0), sub, font=sub_font)
sw2 = sb[2] - sb[0]
sx = (SW - sw2) // 2
sy = ty + (tb[3] - tb[1]) + int(SH * 0.01)
sd.text((sx, sy), sub, fill=DIM, font=sub_font)

out3 = os.path.join(OUT_DIR, "splash.png")
splash.save(out3, "PNG", optimize=True)
print(f"wrote {out3}  ({os.path.getsize(out3):,} bytes)")

# ── 4. favicon.png (64×64) ────────────────────────────────────────────────────
fav = Image.new("RGB", (64, 64), BG)
fd = ImageDraw.Draw(fav)
draw_icon_base(fd, 64)
out4 = os.path.join(OUT_DIR, "favicon.png")
fav.save(out4, "PNG", optimize=True)
print(f"wrote {out4}  ({os.path.getsize(out4):,} bytes)")

print("palette-p1-002: brand asset generation complete.")
